### ISSUE TITLE
Question: Nit Benchmarks

### ISSUE THREAD

**Issue by jwaldrip** [privat/nit#1087]
Do you have any benchmarks of how it compares to other languages?

**Comment by privat** [comment]
We do not have any formal benchmarks.
One may need to do #716 for some kind of _fair_ comparison.

The only recent peer-reviewed thing we have is for subtype tests: http://info.uqam.ca/~privat/publications/TerrasaPrivat-icooolps13-EfficiencyOfSubtypeTest.pdf
More older works are for OO-related implementations http://info.uqam.ca/~privat/publications/DucourEtal-oopsla09-OOImplementation.pdf and http://info.uqam.ca/~privat/publications/PrivatDucour-paste05-LinkTimeStaticAnalysis.pdf

Otherwise, with `nitc --semi-global` I can usually achieve some reasonable performances (in the C/C++ range).
For some IA programs (same algorithms) I have a performance comparable to Java.
Is some bad and unoptimized cases (eg. naive arrays of integers) people can achieve performances between java and python.

Note that because or the FFI, performance is mostly not a problem since it is easy to implement things in C or in another language.
