### ISSUE TITLE
dependencies install error

### ISSUE THREAD

**Issue by Ouajdi** [privat/nit#1182]
I'm using Ubuntu 14.04 LTS and when I try this line:
sudo apt-get install build-essential ccache libgc-dev graphviz libunwind-dev pkg-config

I receive this error message:
 Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libunwind-dev

But with command:
sudo apt-get install build-essential ccache libgc-dev graphviz libunwind8-dev pkg-config

it worked fine, I've just renamed "libunwind-dev" to "libunwind8-dev"
Thank you.

**Comment by R4PaSs** [comment]
Hi,

Yeah we've already experienced the problem, sorry for not fixing that :/

However I'm not sure the proposed fix is safe since the version of
libunwind depends on the OS of the user, and if it is available on the
platform or not

I'm using Debian based mint, and on my machine, libunwind 7 is available
only, on a raspbian, no libunwind is available...

I think maybe we should just remove it altogether and request the end user
to search for his own version depending on his configuration.

Thanks for the hint !

**Comment by privat** [comment]
Thank for the issue.
The list specific list of required packages depends on the distribution and its version, since we cannot list and maintain each distribution, i suggests that we just choose a popular one and suggest to find equivalent packages for the others.

**Comment by MehdiAit** [comment]
The list of dependencys it's availebale for debian 7.x (Wheezy) .

**Comment by privat** [comment]
I udated the website to precise some versions
