### ISSUE TITLE
Dynamic type helps programmer with interpreted languages

### ISSUE THREAD

**Issue by jpcaissy** [privat/nit#1238]
I can't compile this nit code. Please fix.

```
var a = 42
a = "Actually this needs to be a string"
print a
```

I get this error when trying to compile:

```
21:08 ~
jp@debian-vm$ nitg serious_script.nit
serious_script.nit:3,5--40: Type error: expected Int, got String
        a = "Actually this needs to be a string"
            ^
Errors: 1. Warnings: 0.
```

**Comment by R4PaSs** [comment]
Hi again,

In your case the fix is simple, type a with object statically and enjoy
your script ! :)

On a more serious note though, we should consider transferring the type
system to dynamic, this is in my opinion the main weakness of the language,
well aside from what you expressed in #1237 !

**Comment by privat** [comment]
it's a bug in nitc related to niti cf #1236 (in fact no). try:

~~~nit
var a
a = 42
a = "Actually this needs to be a string"
print a
~~~

(yes, this works)

**Comment by privat** [comment]
With

~~~nit
var a = 42
a = "Actually this needs to be a string"
print a
~~~

I get

~~~
  File "x.py", line 1
    var a = 42
        ^
SyntaxError: invalid syntax
~~~

with Python, and

~~~
x.rb:1:in `<main>': undefined method `var' for main:Object (NoMethodError)
~~~

with Ruby, and

~~~
/home/privat/prog/nit/src/parser/x.js:3
print a
      ^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
~~~

with nodejs, and

~~~
var a = 42
a = "Actually this needs to be a string"
print a
~~~

with php... (php, you're so silly...)

Therefore i suspect that the original error is in the program and not in the nit tools since the program does not seems to work even with mainstream dynamically typed languages.
