### ISSUE TITLE
Manipulation of bytes

### ISSUE THREAD

**Issue by privat** [privat/nit#1267]
There should be an abstraction to manipulate bytes and/or sequence of bytes.

Currently Int is used for bit-operation and Text is used as a stream of bytes.
While we can live with the first one modulo #1266 the second one will cause issue with #1262

Maybe a good solution is to provide a specific efficient sequence of bytes and let the other deal with individual bytes as Int.

**Comment by R4PaSs** [comment]
I agree, this need to be done.

More than once (first example I have is websockets for instance) we treat Strings as ByteArrays, this cannot go on anymore.

This structure could provide different ways of accessing its contents in a C-like way ? Thinks like fetch int32 at offset x with little/big endianness ?
It might be useful should someone implement a low-level header file reader/writer like PNG, ELF or other (or for this kind of purposes might as well do it with FFI ? I don't know).

Since we already have NativeString, I guess we could just rename it to ByteArray or use it as the byte manipulator class without renaming, it serves this exact purpose.

**Comment by privat** [comment]
Oh. I did forgot about NativeString that is indeed a simple char* so basically more a sequence of bytes than a text. The idea to use it for both low-level strings and low-level byte sequences is not that crazy.

Trying to read/write a binary format could be a good proof of concept.
One can also think about cryptography or compression that need low-level byte access. 

I also thing that the remark about the FFI is important: we do not need to badly simulate all byte-level data types and operations since the FFI make it easy to interface ourselves with C. It means that maybe we only need to offer basic and simple abstractions for the common usage of byte manipulation.

**Comment by jpages** [comment]
I have done a small library for manipulating bitsets in nit (for perfect hashing). It allowed to access a bitset at a specified offset and a few binary operations.

I suggest to enhance it with real bytes (not integers) and map a Byte with the C-type unsigned char.
The bitset library should also adapt to many size of binary representation.

**Comment by privat** [comment]
closed by #1403 I think
