### ISSUE TITLE
Unable to make NIT without libunwind8-dev

### ISSUE THREAD

**Issue by ventilooo** [privat/nit#1357]
~~~
***************************************************************
* Compile binaries from NIT source files                      *
***************************************************************
./git-gen-version.sh
./nitc_0 --semi-global -v --dir ../bin nitc.nit nitpick.nit nit.nit nitdoc.nit nitls.nit nitunit.nit nitpretty.nit nitmetrics.nit nitx.nit nitlight.nit nitdbg_client.nit nitserial.nit
make[1]: ./nitc_0: Command not found
make[1]: *** [../bin/nitc] Error 127
make[1]: Leaving directory `/home/istvan/nit/src'
make: *** [tools] Error 2
~~~

View with libunwind8

**Comment by Morriar** [comment]
The error seems to indicate that `make` isn't installed on the machine, nothing to do with `libunwind`. Are you pasting the correct error?

**Comment by privat** [comment]
Indeed, the absence of libunwind8-dev ( or libunwind7-dev ) cause the make to fail. But I do not see the point of the issue since 1. it is documented 2. the library is available in most (if not all) distributions.

**Comment by xymus** [comment]
Is this still on Windows? otherwise what is your distribution?

**Comment by xymus** [comment]
For libunwind on Windows, see #1152 for a workaround to desactivate libunwind.

**Comment by ventilooo** [comment]
It was on linux mint 17 this time.

**Comment by ventilooo** [comment]
Once libunwind8-dev install the following problem disapear !

**Comment by R4PaSs** [comment]
I'll rephrase a bit since it is not clear what is reported here.

The main issue here is that the `nitc_0` step completed without a C/make error popping-up, even though the dev library was not installed.

That lead to a `nitc_0 not found` error on the next step.

To see the `include not found` error you'd have to make the C directly from the .nit_compile dir, since the error was not forwarded, it was a bit hard to track the error without knowing the compilation process.

**Comment by privat** [comment]
thanks, the bug make sense now.
