### ISSUE TITLE
Redefined signatures are not checked

### ISSUE THREAD

**Issue by Morriar** [privat/nit#1359]
Example:

~~~nit
class Foo
	fun foo(bar: Int, baz: Bool): String is abstract
end

class Bar
	super Foo

	redef fun foo(bar: Int, baz: Bool) do # forgotten return type?
            return ""
        end
end
~~~

I think that the redef should be raising an error or at least a warning about the return type.

**Comment by privat** [comment]
It is not a bug, it is a feature! Types of the parameter and return types are inherited independently.
Try to redefine with a different return type, or remove the `return` to see it.

The idea was to allow the redefinition of the return type (that is allowed in a covariant way) while inhering the parameter type (because they are invariant so superfluous to repeat).

I need a seconder or something if you want a change in the feature. :)

**Comment by Morriar** [comment]
Ok, I understand and it makes sense. I close the issue.
