### ISSUE TITLE
2D arrays

### ISSUE THREAD

**Issue by Bl4ckb0ne** [privat/nit#1496]
Is there a Vector 2D class or some doc about an Array[Array[T]] somewhere?
Anyway, I'm converting [this](https://gist.github.com/Bl4ckb0ne/f498d68d33ef6d7ba1bc) from Haxe to nit, if anybody wants it I'll paste it here

**Comment by Morriar** [comment]
I don't remember something like this in the stdlib. You should make a pull request with it!

**Comment by R4PaSs** [comment]
I see what you're doing, and this feels close to what was achieved with [MultiHashMap](http://nitlanguage.org/doc/stdlib/class_more_collections-__MultiHashMap.html)

Maybe we should consider adding something like this to `more_collections`, or not since we can always do a `new Array[Array[E]]`.

For your question, a 2D array is declared in Nit much like in other languages, using `Array[Array[E]]`, and for each row of your Matrix, you have to manually instantiate a `new Array[E]` before adding something to it.

What bothers me though is that if we choose to support some kind of 2DArray or 2DVector or 2DMatrix, whatever the name, then we should propose 3D, 4D and so on for cohesiveness.

I think this will pollute lib more than anything, but I guess this is a common problem and maybe it should be addressed within the lib.

@Morriar seems to agree to see such a collection in lib, I don't know what the others think of it ?

**Comment by Bl4ckb0ne** [comment]
Weel, at least I''l do it on local, we can talk about it next time.

BTW, is there an equivalent for fflush(stdout) and usleep for nit? Both of the functions are from the C stdlib

**Comment by R4PaSs** [comment]
For `usleep` => [nanosleep](http://nitlanguage.org/doc/stdlib/property_standard__kernel__Sys__nanosleep.html#standard__time__Sys__nanosleep)

For fflush => I guess it's missing ! Though it could be a welcome addition on streams, i'll see to it

**Comment by Bl4ckb0ne** [comment]
I'm trying to do a [Conway's Game of Life](http://rosettacode.org/wiki/Conway's_Game_of_Life), but it's gonna be hard.

**Comment by R4PaSs** [comment]
I would not bet on that !

By design, a `\n` character should provoke a flush, in this regard it would be flushed accordingly when an iteration is done, i'd think you would not have issues with that

**Comment by Bl4ckb0ne** [comment]
Can somebody help me with the declaration of a class?
I don't understand how to declare a var private or public, and how to declare a constructor.
ATM I got this, but it gaves me a stacktrace at the grid loop.
 ```nit
class Vector2D[E]
    var width:Int 
    var height:Int 
    var grid:Array[E] is noinit
  
    init
    do
         for i in [0..width*height] do
             grid[i] = 0                                                                       
         end
    end
end 
```

**Comment by privat** [comment]
At the begin of the init

~~~nit
grid = new Array[E].with_capacity(width*height)
~~~

often, it is better to instantiate object before trying to use them. :)

`with_capacity` is optional but here will prepare the memory (thus avoid reallocation in the future additions).

But, since you want to fill with 0 I propose that you replace the full init body with the single following line

~~~nit
grid = new Array[E].filled_with(0, width*height)
~~~

**Comment by Bl4ckb0ne** [comment]
Works perfectly, thanks a lot

**Comment by Bl4ckb0ne** [comment]
I kinda finished it for now
```nit
class Vector2D[E]
    var width:Int 
    var height:Int

    var grid:Array[E] is noinit

    init do
        grid = new Array[E].filled_with(0, width*height)
    end

    fun get(x:Int, y:Int):E do
        return grid[y * width + x]
    end

    fun set(x:Int, y:Int, value:E) do
        grid[y * width + x] = value
    end
    
    fun display do
        for i in [0..height-1] do
            var out = new Buffer
            for j in [0..width-1] do
                out.append(get(i, j).to_s)
                out.add(' ')
            end
            print out.write_to_string
        end
    end
end
```

Also, I didn't found a int to bool function in the standard library, so I made one
```nit

redef class Int 
    fun to_bool:Bool do
        if self == 0 then return false
        return true
    end
end
```

**Comment by R4PaSs** [comment]
You can simplify your `to_bool` method :)

~~~nit
redef class Int
    fun to_bool do return self != 0
end
~~~

There you have it !

For the to_bool method, it can be useful to have it in the standard library, I'd suggest you make a PR with this addition

**Comment by Bl4ckb0ne** [comment]
I'll do this this afternoon.
What do I need to make a good PR?

**Comment by R4PaSs** [comment]
You can take at look at our guidelines for [contributing](http://nitlanguage.org/internal/)

Long story short:

* Make sure to have clean, independant and self-documenting commits
* Document your PR with a short cover letter when you push it on Github
* Sign-off your commits, and make your your code does not contain superfluous whitespaces (git can help you for that)
