### ISSUE TITLE
Crash in RTA

### ISSUE THREAD

**Issue by xymus** [privat/nit#1512]
This program makes `nitc` crash in the rapid type analysis:

~~~nit
var x = null
if x != null then
	assert x isa String # Here is the cause
end
~~~

~~~
Runtime error: Cast failed (rapid_type_analysis.nit:627)
-------------------------------------------------
--   Stack Trace   ------------------------------
-------------------------------------------------
` fatal_exit
` nit::rapid_type_analysis#AIsaExpr#::rapid_type_analysis::ANode::accept_rapid_type_visitor (rapid_type_analysis.nit:625)
` nit#RapidTypeVisitor#Visitor::visit (rapid_type_analysis.nit:456)
` nit#Visitor#enter_visit (parser/parser_nodes.nit:413)
` nit::parser_prod#AAssertExpr#ANode::visit_all (parser/parser_prod.nit:3399)
` nit#Visitor#enter_visit (parser/parser_nodes.nit:413)
` nit#ANodes#visit_all (parser/parser_nodes.nit:289)
` nit::parser_prod#ABlockExpr#ANode::visit_all (parser/parser_prod.nit:2514)
` nit#Visitor#enter_visit (parser/parser_nodes.nit:413)
` nit::parser_prod#AIfExpr#ANode::visit_all (parser/parser_prod.nit:2908)
` nit#Visitor#enter_visit (parser/parser_nodes.nit:413)
` nit#ANodes#visit_all (parser/parser_nodes.nit:289)
` nit::parser_prod#ABlockExpr#ANode::visit_all (parser/parser_prod.nit:2514)
` nit#Visitor#enter_visit (parser/parser_nodes.nit:413)
` nit#Visitor#enter_visit (parser/parser_nodes.nit:413)
` nit#RapidTypeAnalysis#run_analysis (rapid_type_analysis.nit:188)
` nit::rapid_type_analysis#ModelBuilder#do_rapid_type_analysis (rapid_type_analysis.nit:34)
` nit#SeparateCompilerPhase#Phase::process_mainmodule (compiler/separate_compiler.nit:105)
` nit::modelbuilder#ToolContext#run_global_phases (modelbuilder.nit:52)
` nit::abstract_compiler#standard::Sys#main (compiler/abstract_compiler.nit:3297)
` main
` __libc_start_main
` _start
` 
-------------------------------------------------
~~~

**Comment by privat** [comment]
well spotted. #1257 relaxed some rules about untyped code in order to allow the compiler to compute a fixed point. So an inconsistent state with untyped code is now permitted (imagine that the if is in a loop and that the value of x is assigned after, making the `then` part live on second roud of the analysis). The problem is that it never checks that there is no remaining untyped code at the end of the analysis (that can display a nice error message for instance.). If you run with `-vv` you will likely see a lot of *No return type but no error.* debug messages during the compilation as the compiler is analyzing strange code (expressions without a static type but without any error message generated).

The fact that a type-test fails (and not a simple x.foo of something) is because the series on `--keep-going` forgot to harden the special type-test case.
By the way, you can replace your assert by `x = x.as(String)` that is hardened and will compile nicely :)

Related with #1439 because they will likely be closed together (one day)
